version: '2'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
  mongo:
    image: 'mongo:4.0'
    container_name: 'test'
    mem_limit: 512M
    ports:
      - "27417:27017"
    volumes:
      - ./.data/mongo/data:/data/db
    logging:
      driver: json-file
      options:
        max-size: 1k
